; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = alarm, actuator, temperature
src_dir = src

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
lib_deps = 
    Wire
    arduino-libraries/Servo
build_flags =
    -Wall
    -Os

[env:alarm]
build_src_filter = -<*> +<alarm/>
; extra_scripts = 
;     pre:scripts/alarm.py
build_flags =
    ${env.build_flags}
    -DNODE_TYPE=ALARM
    -DNODE_ID=1
    -DI2C_SLAVE_ADDR=0X08

[env:actuator] 
build_src_filter = -<*> +<actuator/>
; extra_scripts = 
;     pre:scripts/base.py
;     pre:scripts/actuator.py
build_flags =
    ${env.build_flags}
    -DNODE_TYPE=ACTUATOR
    -DNODE_ID=2
    -DI2C_SLAVE_ADDR=0X09

[env:temperature]
build_src_filter = -<*> +<temperature/>
; extra_scripts = 
;     pre:scripts/base.py
;     pre:scripts/temperature.py
build_flags = 
    ${env.build_flags}
    -DNODE_TYPE=TEMPERATURE
    -DNODE_ID=3
    -DI2C_SLAVE_ADDR=0X0A
