name: Firmware CI

on:
  push:
  pull_request:

jobs:
  build-arduino:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build Arduino Firmware
        working-directory: arduino
        run: platformio run

  build-esp32:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build ESP32 Firmware
        working-directory: master_esp32
        run: platformio run